//Auth
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const GET_PROFILE_USER = "GET_PROFILE_USER";
export const GET_PROFILE_USER_SUCCESS = "GET_PROFILE_USER_SUCCESS";
export const GET_PROFILE_USER_ERROR = "GET_PROFILE_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
//Course
export const GET_COURSES="GET_COURSES";
export const GET_COURSES_SUCCESS="GET_COURSES_SUCCESS";
export const GET_COURSES_ERROR="GET_COURSES_ERROR";
export const GET_COURSES_TEACHER="GET_COURSES_TEACHER";
export const GET_COURSES_SUCCESS_TEACHER="GET_COURSES_SUCCESS_TEACHER";
export const GET_COURSES_ERROR_TEACHER="GET_COURSES_ERROR_TEACHER";
export const GET_COURSES_SEMETER="GET_COURSES_SEMETER";
export const GET_COURSES_SUCCESS_SEMETER="GET_COURSES_SUCCESS_SEMETER";
export const GET_COURSES_ERROR_SEMETER="GET_COURSES_ERROR_SEMETER";
export const GET_COURSE_ID_SUCCESS="GET_COURSE_ID_SUCCESS";
export const GET_COURSE_ID_ERROR="GET_COURSE_ID_ERROR";
export const GET_COURSE_ID="GET_COURSE_ID";
export const ADD_COURSE="ADD_COURSE";
export const ADD_COURSE_SUCCESS="ADD_COURSE_SUCCESS";
export const ADD_COURSE_ERROR="ADD_COURSE_ERROR";
export const EDIT_COURSE="EDIT_COURSE";
export const EDIT_COURSE_SUCCESS="EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_ERROR="EDIT_COURSE_ERROR";
export const DELETE_COURSE="DELETE_COURSE";
export const DELETE_COURSE_SUCCESS="DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_ERROR="DELETE_COURSE_ERROR";


// CLASS
export const GET_CLASSES_SUCCESS="GET_CLASSES_SUCCESS";
export const GET_CLASSES_ERROR="GET_CLASSES_ERROR";
export const GET_CLASSES="GET_CLASSES";
export const GET_CLASSES_SUCCESSV1="GET_CLASSES_SUCCESSV1";
export const GET_CLASSES_ERRORV1="GET_CLASSES_ERRORV1";
export const GET_CLASSESV1="GET_CLASSESV1";
export const GET_CLASS_ID_SUCCESS="GET_CLASS_ID_SUCCESS";
export const GET_CLASS_ID_ERROR="GET_CLASS_ID_ERROR";
export const GET_CLASS_ID="GET_CLASS_ID";
export const ADD_CLASS="ADD_CLASS";
export const ADD_CLASS_SUCCESS="ADD_CLASS_SUCCESS";
export const ADD_CLASS_ERROR="ADD_CLASS_ERROR";
export const EDIT_CLASS="EDIT_CLASS";
export const EDIT_CLASS_SUCCESS="EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_ERROR="EDIT_CLASS_ERROR";
export const DELETE_CLASS="DELETE_CLASS";
export const DELETE_CLASS_SUCCESS="DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_ERROR="DELETE_CLASS_ERROR";

//SUBJECT
export const GET_SUBJECTS_SUCCESS="GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_ERROR="GET_SUBJECTS_ERROR";
export const GET_SUBJECTS="GET_SUBJECTS";
export const GET_SUBJECTS_SUCCESSV1="GET_SUBJECTS_SUCCESSV1";
export const GET_SUBJECTS_ERRORV1="GET_SUBJECTS_ERRORV1";
export const GET_SUBJECTSV1="GET_SUBJECTSV1";
export const GET_SUBJECT_ID_SUCCESS="GET_SUBJECT_ID_SUCCESS";
export const GET_SUBJECT_ID_ERROR="GET_SUBJECT_ID_ERROR";
export const GET_SUBJECT_ID="GET_SUBJECT_ID";
export const ADD_SUBJECT="ADD_SUBJECT";
export const ADD_SUBJECT_SUCCESS="ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_ERROR="ADD_SUBJECT_ERROR";
export const EDIT_SUBJECT="EDIT_SUBJECT";
export const EDIT_SUBJECT_SUCCESS="EDIT_SUBJECT_SUCCESS";
export const EDIT_SUBJECT_ERROR="EDIT_SUBJECT_ERROR";
export const DELETE_SUBJECT="DELETE_SUBJECT";
export const DELETE_SUBJECT_SUCCESS="DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR="DELETE_SUBJECT_ERROR";

// USER
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_ERROR="GET_USERS_ERROR";
export const GET_USERS="GET_USERS";
export const GET_USER_ID_SUCCESS="GET_USER_ID_SUCCESS";
export const GET_USER_ID_ERROR="GET_USER_ID_ERROR";
export const GET_USER_ID="GET_USER_ID";
export const ADD_USER="ADD_USER";
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";
export const ADD_USER_ERROR="ADD_USER_ERROR";
export const DELETE_USER="DELETE_USER";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR="DELETE_USER_ERROR";

//STUDENT
export const GET_STUDENTS_SUCCESS="GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_ERROR="GET_STUDENTS_ERROR";
export const GET_STUDENTS="GET_STUDENTS";
export const GET_STUDENTS_COURCE_SUCCESS="GET_STUDENTS_COURCE_SUCCESS";
export const GET_STUDENTS_COURCE_ERROR="GET_STUDENTS_COURCE_ERROR";
export const GET_STUDENTS_COURCE="GET_STUDENTS_COURCE";

export const GET_STUDENTS_SCHEDULE_SUCCESS="GET_STUDENTS_SCHEDULE_SUCCESS";
export const GET_STUDENTS_SCHEDULE_ERROR="GET_STUDENTS_SCHEDULE_ERROR";
export const GET_STUDENTS_SCHEDULE="GET_STUDENTS_COURCE";

export const GET_STUDENT_ID_SUCCESS="GET_STUDENT_ID_SUCCESS";
export const GET_STUDENT_ID_ERROR="GET_STUDENT_ID_ERROR";
export const GET_STUDENT_ID="GET_STUDENT_ID";
export const ADD_STUDENT="ADD_STUDENT";
export const ADD_STUDENT_SUCCESS="ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR="ADD_STUDENT_ERROR";

export const EDIT_STUDENT="EDIT_STUDENT";
export const EDIT_STUDENT_SUCCESS="EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR="EDIT_STUDENT_ERROR";
export const DELETE_STUDENT="DELETE_STUDENT";
export const DELETE_STUDENT_SUCCESS="DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR="DELETE_STUDENT_ERROR";


// TEACHERS
export const GET_TEACHERS_SUCCESS="GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR="GET_TEACHERS_ERROR";
export const GET_TEACHERS="GET_TEACHERS";
export const GET_TEACHERS_SUCCESSV1="GET_TEACHERS_SUCCESSV1";
export const GET_TEACHERS_ERRORV1="GET_TEACHERS_ERRORV1";
export const GET_TEACHERSV1="GET_TEACHERSV1";

// SCHEDULE

export const GET_SCHEDULE_SUCCESS="GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_ERROR="GET_SCHEDULE_ERROR";
export const GET_SCHEDULE="GET_SCHEDULE";
export const ADD_SCHEDULE="ADD_SCHEDULE";
export const ADD_SCHEDULE_SUCCESS="ADD_SCHEDULE_SUCCESS";
export const ADD_SCHEDULE_ERROR="ADD_SCHEDULE_ERROR";
export const EDIT_SCHEDULE="EDIT_SCHEDULE";
export const EDIT_SCHEDULE_SUCCESS="EDIT_SCHEDULE_SUCCESS";
export const EDIT_SCHEDULE_ERROR="EDIT_SCHEDULE_ERROR";
export const DELETE_SCHEDULE="DELETE_SCHEDULE";
export const DELETE_SCHEDULE_SUCCESS="DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_ERROR="DELETE_SCHEDULE_ERROR";
export const SAVE_SCHEDULE ="SAVE_SCHEDULE";

// 
export const GET_NOTIFICATIONS_SUCCESS="GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_ERROR="GET_NOTIFICATIONS_ERROR";
export const GET_NOTIFICATIONS="GET_NOTIFICATIONS";
export const EDIT_NOTIFICATION="EDIT_NOTIFICATION";
export const EDIT_NOTIFICATION_SUCCESS="EDIT_NOTIFICATION_SUCCESS";
export const EDIT_NOTIFICATION_ERROR="EDIT_NOTIFICATION_ERROR";
export const DELETE_NOTIFICATION="DELETE_NOTIFICATION";
export const DELETE_NOTIFICATION_SUCCESS="DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_ERROR="DELETE_NOTIFICATION_ERROR";


// RegisterCourse
export const GET_RCSTUDENT_SUCCESS="GET_RCSTUDENT_SUCCESS";
export const GET_RCSTUDENT_ERROR="GET_RCSTUDENT_ERROR";
export const GET_RCSTUDENT="GET_RCSTUDENT";

export const GET_COURCEBYKEY_SUCCESS="GET_COURCEBYKEY_SUCCESS";
export const GET_COURCEBYKEY_ERROR="GET_COURCEBYKEY_ERROR";
export const GET_COURCEBYKEY="GET_COURCEBYKEY";
export const GET_STUDENTBYKEY_SUCCESS="GET_STUDENTBYKEY_SUCCESS";
export const GET_STUDENTBYKEY_ERROR="GET_STUDENTBYKEY_ERROR";
export const GET_STUDENTBYKEY="GET_STUDENTBYKEY";
export const ADD_RCSTUDENT="ADD_RCSTUDENT";
export const ADD_RCSTUDENT_SUCCESS="ADD_RCSTUDENT_SUCCESS";
export const ADD_RCSTUDENT_ERROR="ADD_RCSTUDENT_ERROR";
export const CONFIRM_RCSTUDENT="CONFIRM_RCSTUDENT";
export const CONFIRM_RCSTUDENT_SUCCESS="CONFIRM_RCSTUDENT_SUCCESS";
export const CONFIRM_RCSTUDENT_ERROR="CONFIRM_RCSTUDENT_ERROR";