export const routes = [
  {
    id: "1",
    icon: "course",
    name: "Khóa học",
    route: "/",
    role: "any",
  },
  {
    id: "2",
    icon: "team",
    name: "Người dùng",
    route: "/user",
    role: "admin",
  },
  {
    id: "12",
    menuParentId: "2",
    icon: "user",
    name: "Học viên",
    route: "/nguoi_dung/hoc_vien",
    role: "admin",
  },
  {
    id: "13",
    menuParentId: "2",
    icon: "user",
    name: "Quản trị",
    route: "/nguoi_dung/quan_tri",
    role: "admin",
  },
  {
    id: "3",
    icon: "home",
    name: "Phòng học",
    route: "/phong_hoc",
    role: "admin",
  },
  {
    id: "5",
    icon: "book",
    name: "Môn học",
    route: "/mon_hoc",
    role: "admin",
  },
  {
    id: "14",
    icon: "group",
    name: "Khóa học giáo viên",
    route: "/khoa_hoc-giao_vien/:id",
    role: "any",
  },
  {
    id: "15",
    icon: "group",
    name: "Học viên khóa học",
    route: "/hoc_vien-khoa_hoc/:id",
    role: "any",
  },
  {
    id: "16",
    icon: "schedule",
    name: "Lịch học",
    route: "/lich_hoc",
    role: "any",
  },
  {
    id: "17",
    icon: "request",
    name: "Yêu cầu",
    route: "/yeu_cau",
    role: "admin",
  },
  {
    id: "18",
    icon: "request",
    name: "Học viên lịch học",
    route: "/lich_hoc-hoc_vien/:id",
    role: "any",
  },
  {
    id: "19",
    icon: "request",
    name: "Đăng ký khóa học",
    route: "/dang_ky-khoa_hoc",
    role: "admin",
  },
];
